### ISSUE TITLE
Bash file not running

### ISSUE THREAD

**Issue by shubhankarpataskar** [SICKAG/sick_scan_base#10]
When I try to run the .bash file, i ended up with this error.

![Screenshot from 2021-04-07 14-22-10](https://user-images.githubusercontent.com/34801128/114792220-c8f48a00-9d3c-11eb-937f-42ccd9230cc4.png)

Is there anything I need to rectify?
Working on Ubuntu 20.04, ROS Noetic and connected to SICK TIM 581 LiDAR

**Comment by michael1309** [comment]
You should use sick_scan, if you like to use the Lidar together with ROS.

**Comment by shubhankarpataskar** [comment]
I did run the sick_scan command before that, but didn't get any result.
My objective is to get data from the LiDAR and compile on C++.

**Comment by michael1309** [comment]
You can try to use it without the simulation. 
If ROS installed you can also retry to use with the repo. https://github.com/SICKAG/sick_scan

**Comment by shubhankarpataskar** [comment]
I did try it with ROS, But via the sick_scan_base I would like to get the csv file data. 
Is there any way? 
Also via sick_scan, how to obtain the data in real time?

**Comment by rostest** [comment]
@shubhankarpataskar  Thanks for your report! The script fails, because `sick_generic_caller` wasn't found in build-folder `build_x64`. There are two slightly different ways to build and run the simulation:

1. Build in folder  `build`:
```
cd ./build
cmake -G "Unix Makefiles" ..
make
```
Run the simulation:
```
python3 ./test/emulator/test_server.py --scandata_file=./test/emulator/scandata/20210302_lms511.pcapng.scandata.txt --scandata_frequency=20.0 --tcp_port=2112 &
sleep 1
./build/sick_generic_caller ./launch/sick_lms_5xx.launch hostname:=127.0.0.1
```

2. Alternative: use the scripts in folder `test/scripts` and build in folder  `build_x64`:
```
cd ./test/scripts
./makeall.bash
./run_simu_lms_5xx.bash
```

Both alternatives work the same, but just use different build folder ( `build` resp.  `build_x64`). We'll update the scripts to use folder `build` consistently. Please use one of the two alternatives in the meantime.

**Comment by shubhankarpataskar** [comment]
![Screenshot from 2021-04-23 15-42-00](https://user-images.githubusercontent.com/34801128/115936717-ddc2d300-a44a-11eb-99c6-f7bb634389ac.png)

So this is coming when i ran the script again on another workspace.

**Comment by rostest** [comment]
The error message `Address already in use` means that another process is already using TCP port 2112. Most probably another instance of test_server.py is still running, but it might be other software using this port as well.
Use 
```
netstat -ltnp | grep 2112
```
to find the process using tcp port 2112. Then kill this process and restart
```
python3 ./test/emulator/test_server.py --scandata_file=./test/emulator/scandata/20210302_lms511.pcapng.scandata.txt --scandata_frequency=20.0 --tcp_port=2112
```

Instead of starting processes in background by script `run_simu_lms_5xx.bash`, you can do the same be running `test_server.py` and `sick_generic_caller` in different terminals. Just start one terminal in directory `sick_scan_base` and start `python3 ./test/emulator/test_server.py --scandata_file=./test/emulator/scandata/20210302_lms511.pcapng.scandata.txt --scandata_frequency=20.0 --tcp_port=2112`. Wait a second to be sure that test_server.py is up and running. Then open another terminal in `sick_scan_base` and run `./build/sick_generic_caller ./launch/sick_lms_5xx.launch hostname:=127.0.0.1 sw_pll_only_publish:=False`. Please make sure that test_server.py and sick_generic_caller have been finished or killed before restarting them. If in doubt, you can kill both with
```
pkill -f ./test/emulator/test_server.py
killall sick_generic_caller
```
